### ISSUE TITLE
Neqo sometimes fails to establish connection in case of high packet loss

### ISSUE THREAD

**Issue by vonasek** [mozilla/neqo#631] opened 2020-05-14 13:26 UTC
[neqo-client.log.gz](https://github.com/mozilla/neqo/files/4628653/neqo-client.log.gz)

handshakeloss test occasionally fails at https://github.com/mozilla/neqo/blob/141c232d1227001fb53254b84893b071719485d2/neqo-client/src/main.rs#L719, because connecting times out

**Comment by agrover** [comment] 2020-05-15 06:13
How occasionally? Marten says it can happen but only _very_ rarely.

**Comment by martinthomson** [comment] 2020-05-15 06:56
I think that we should start with the assumption that we have a bug and try to diagnose the cause.

**Comment by marten-seemann** [comment] 2020-05-15 07:10
It's quite helpful to load the qlog into qvis. quic-go exports qlogs for every connection. That alone should be helpful for debugging already. Even better if you have qlogs as well.

**Comment by vonasek** [comment] 2020-05-15 08:22
> How occasionally? Marten says it can happen but only _very_ rarely.

I've hit it 4 times in 187 runs.

**Comment by marten-seemann** [comment] 2020-05-15 08:31
In this test case, the network simulator drops packets with a 30% probability (in both directions). Depending on your initial RTT estimate and your handshake timeout you can calculate how many probes would need to get dropped for the test to fail. 4 in 187 seems a bit high to me.

**Comment by vonasek** [comment] 2020-05-15 08:48
> > How occasionally? Marten says it can happen but only _very_ rarely.
> 
> I've hit it 4 times in 187 runs.

I forgot to note that I reduced number of requests in the test from 50 to 10 on my host. The numbers would be higher with unchanged test.

**Comment by agrover** [comment] 2020-07-01 19:07
@vonasek would you be so kind as to retest with latest code? If still there, can you post client & server qlogs?

**Comment by agrover** [comment] 2020-07-14 17:18
dupe/related to #799

**Comment by ddragana** [comment] 2021-11-24 12:21
Closing this issue. We can open another one if needed.

**Closed by ddragana** 2021-11-24 12:21 UTC
Labels: bug
