### ISSUE TITLE
assertion failed: earliest > now

### ISSUE THREAD

**Issue by vonasek** [mozilla/neqo#621] opened 2020-05-12 16:10 UTC
[neqo-client.log](https://github.com/mozilla/neqo/files/4616805/neqo-client.log)

I hit this almost all the time when running handshakeloss qns test. This log is from [pacing branch](https://github.com/martinthomson/neqo/tree/pacing) because in PR [#618](https://github.com/mozilla/neqo/pull/618) was mentioned that it should fix issue [#177](https://github.com/mozilla/neqo/issues/177), but it didn't. Latest master branch fails in the same way.

**Comment by martinthomson** [comment] 2020-05-13 00:15
I think that I tracked this down.  The logic for setting the loss detection timer was considering packets that we were still tracking, but had already called lost.  That might be the real cause of #177.

I want to write a test to reproduce this, but it shouldn't take too long.

**Comment by vonasek** [comment] 2020-05-13 22:23
[neqo-client.log](https://github.com/mozilla/neqo/files/4625021/neqo-client.log)

It still fails with latest master with patches from PR #623 and PR #624.

**Comment by martinthomson** [comment] 2020-05-14 02:20
The fix in #623 should have fixed this, but I see that it didn't.

If you look at the logs, there is a packet that is being marked as lost:

```
0s302ms DEBUG lost=1, time sent Instant { tv_sec: 1687426, tv_nsec: 868569885 } ...
```

The loss delay is 57.609337ms, which means a loss detection would be set for `Instant { tv_sec: 1687426, tv_nsec: 926179222 }` if that packet were considered for that timer.  #623 ensures that doesn't happen.  But the timer we have is instead:

```
[LossRecovery] next_timeout loss=Some(Instant { tv_sec: 1687426, tv_nsec: 945040757 }) pto=...
```

If the loss delay is the same (it's based on the RTT, and we have no new RTT samples between the calls), then this refers to `Instant { tv_sec: 1687426, tv_nsec: 887431420 }` which is exactly when we sent a STREAM frame in the application data space.  That was packet number ap0.

That's the clue.  We don't receive any ACK frames for application data, so no packets have been lost.

So we need a new fix on top of that in #623 to make this ignore packets > `largest_acknowledged` for the space.  Because we enable timed loss recovery only for packets sent before the `largest_acknowledged`.  In this case, `largest_acknowledged` is `None`, so we should not be reporting any time for the application data space.

**Comment by martinthomson** [comment] 2020-05-14 07:38
OK, easy code fix, horrible test.  @vonasek, I'd appreciate it if you could let me know how #623 goes for you.

**Comment by vonasek** [comment] 2020-05-14 08:15
I ran the test 10 times and didn't hit the assertion. I'll keep running the test for a while and let you know.

**Comment by martinthomson** [comment] 2020-05-14 09:46
Great news.  Maybe I've squashed the last of these bugs.

**Comment by vonasek** [comment] 2020-05-14 14:57
I couldn't reproduce it in about 200 runs.

**Closed** 2020-05-15 01:10 UTC
Labels: bug
