### ISSUE TITLE
Redo #1784

### ISSUE THREAD

**Issue by larseggert** [mozilla/neqo#1801] opened 2024-04-09 05:46 UTC
@KershawChang said in #1800:
> It appears that PR #1784 caused some [test failures](https://treeherder.mozilla.org/jobs?repo=try&revision=a0f4127144add8869a3297beb2562a5b8069abbc) (failed tests on windows). After reverting it, all http3 tests are [passed](https://treeherder.mozilla.org/jobs?repo=try&revision=c20146ce755c3926174142aeb0071290931d3818).

We should find out why those treeherder tests failed, and write a neqo unittest that replicates that failure. And then take another stab at #1784.

**Comment by mxinden** [comment] 2024-04-09 07:10
Sorry for the trouble @kershawchang.

Do I understand correctly, that the failing tests all use https://searchfox.org/mozilla-central/source/netwerk/test/http3server/src/main.rs?

**Comment by KershawChang** [comment] 2024-04-09 07:20
> Do I understand correctly, that the failing tests all use https://searchfox.org/mozilla-central/source/netwerk/test/http3server/src/main.rs?

Yes, that's correct.
Note that those tests are only failed on windows platform, so I assume this could be a timing issue, which makes it not easy to debug. Or it could be the fault of our flaky test server that needs to be modified.

**Comment by mxinden** [comment] 2024-04-12 08:13
If I understand correctly the GitHub HTTP3 server implementation (`neqo-bin/server/mod.rs`) and the mozilla-central HTTP3 server implementation have a lot in common, e.g.:

- wrapper logic around `neqo-http3` driving `neqo_http3::Http3Server`
- UDP I/O logic

What is the long term plan for the two? Should they simply co-exist as they do today? Should they merge? Should they share components?

**Comment by larseggert** [comment] 2024-04-15 05:24
Good topic to discuss on the next call. I don't have history of why the current state is as it is, but I'd personally like to reduce duplication as much as possible, and ideally have most of the logic in the neqo repo where we can more easily update and test it.

(We should probably add a CI step to build Fx with PRs that propose changes to neqo, and ideally also have some Fx-level tests.)

**Comment by KershawChang** [comment] 2024-04-15 07:23
> 
> What is the long term plan for the two? Should they simply co-exist as they do today? Should they merge? Should they share components?

It's probably not easy to merge the two, but sharing some components and reducing the duplicate code definitely makes sense to me.

**Comment by mxinden** [comment] 2024-04-15 08:21
> Good topic to discuss on the next call.

Added to the agenda document :heavy_check_mark:.

**Comment by KershawChang** [comment] 2024-04-22 14:09
I’ve investigated this issue and believe it is caused by a design flaw in our test [http3server](https://searchfox.org/mozilla-central/rev/863aef60f9fa1536884252ad90cad1d8ee9d8a41/netwerk/test/http3server/src/main.rs). Specifically, with the changes introduced in #1784, the [Http3Server::process](https://github.com/mozilla/neqo/blob/4fc4d16744ede5b099dd5bb4bfd5922d07deb046/neqo-http3/src/server.rs#L116) method sometimes returns `Output::None`. This behavior is problematic for the `http3server`, which depends on the [process_datagrams_and_events](https://searchfox.org/mozilla-central/rev/863aef60f9fa1536884252ad90cad1d8ee9d8a41/netwerk/test/http3server/src/main.rs#1264) method being called periodically. However, [process_datagrams_and_events is only triggered when a timer expires or a packet is received](https://searchfox.org/mozilla-central/rev/863aef60f9fa1536884252ad90cad1d8ee9d8a41/netwerk/test/http3server/src/main.rs#1325,1347). This could lead to stalls.

I think the right fix would be to refactor the `http3server` such  that `process_datagrams_and_events` is called when there is data to send.

**Comment by mxinden** [comment] 2024-05-27 10:51
With https://github.com/mozilla/neqo/pull/1878 merged and https://bugzilla.mozilla.org/show_bug.cgi?id=1895319 closed, this issue can be closed as well. Would you mind @larseggert?

**Closed** 2024-05-27 11:10 UTC
